# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_auto_20180630_1441'),
        ('mcq', '0003_auto_20180630_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('questions', models.ManyToManyField(to='mcq.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.Learner')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Tournament')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipation',
            unique_together=set([('learner', 'tournament')]),
        ),
    ]
