# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-30 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
